COMPONENT=BaseStationC
CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS += -DCC2420_NO_ADDRESS_RECOGNITION
CFLAGS += -DTASKLET_IS_TASK
PFLAGS = -DCC2420_DEF_CHANNEL=20

include $(MAKERULES)
CFLAGS += -I$(TOSDIR)/lib/printf
